name: ci

on:
  push:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - 
        name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index

      - name: Build and export to Docker
        uses: docker/build-push-action@v6
        with:
          context: "https://github.com/Sagar2366/docker-awesome-projects.git#main:project3"
          file: Dockerfile
          load: true
          tags: weatherapp:testimage
      
      - name: Test
        run: |
          docker run --rm weatherapp:testimage

      - name: Docker Scout
        id: docker-scout
        uses: docker/scout-action@v1
        with:
          command: cves,recommendations,compare
          to-latest: true
          ignore-base: true
          ignore-unchanged: true
          only-fixed: true
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "https://github.com/Sagar2366/docker-awesome-projects.git#main:project3"
          push: true
          annotations: ${{ steps.meta.outputs.annotations }}
          provenance: mode=max
          tags: ${{ vars.DOCKERHUB_USERNAME }}/dockerweather:${{ steps.meta.outputs.tags }}
          
      - 
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
